spring.application.name=movie-info-service
server.port=8082

api.key=${TMDB_API_KEY:b0af84324ea41ca39f4311c9156e94e3}

cache.enabled=${CACHE_ENABLED:true}
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/movieinfo}

# Eureka
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka}