spring.application.name=trending-movies-service
server.port=8084

grpc.server.port=9084

ratings.grpc.host=${RATINGS_GRPC_HOST:localhost}
ratings.grpc.port=9083

# Eureka
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka}