spring.application.name=movie-catalog-service
server.port=8081
management.endpoints.web.exposure.include=hystrix.stream

trending.grpc.host=${TRENDING_GRPC_HOST:localhost}
trending.grpc.port=9084

# Eureka
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka}